# Seniority Levels
SENIORITY_UNDETERMINED = 0
SENIORITY_LOW = 1
SENIORITY_MIDDLE = 2
SENIORITY_HIGH = 3

# Percentile Thresholds for Seniority
NUM_PUBS_TOP_PERC_SENIORITY = 30
NUM_CITATIONS_TOP_PERC_SENIORITY = 30

# Column Names
COLUMN_NUMBER_PUBLICATIONS = 'NUMBER_PUBLICATIONS'
COLUMN_NUMBER_CITATIONS = 'NUMBER_CITATIONS'
COLUMN_EXPERIENCE_REVIEWER = 'EXPERIENCE_REVIEWER'
COLUMN_EXPERIENCE_PANEL = 'EXPERIENCE_PANEL'
COLUMN_SENIORITY = 'SENIORITY'


